# Generated by Django 6.0.1 on 2026-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_blockedip_city_blockedip_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='blockedip',
            name='country',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
